version: 2.1

orbs:
  node: circleci/node@5.0.1
  gcp-cli: circleci/gcp-cli@2.4.0

jobs:
  test_and_build:
    docker:
      - image: cimg/node:16.15.0
    resource_class: medium
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Generate schema
          command: yarn generate-schema
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Prepare tests
          command: yarn workspace @standup/common build
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run build
          command: yarn build

  deploy:
    executor: gcp-cli/google
    steps:
      - add_ssh_keys:
          fingerprints:
            - '5c:90:f9:10:c6:6c:f6:c2:0c:b1:89:89:a1:a3:73:f0'
      - gcp-cli/initialize
      - run:
          name: list ssh
          command: ls -laih ~/.ssh/config
      - run:
          name: Connect to VM
          command: ssh -o "StrictHostKeyChecking no" $USERNAME@$SERVER "
            cd standup-api/;
            git pull;
            source /home/$USERNAME/.nvm/nvm.sh
            echo $PATH;
            echo $USER;
            node --version;
            yarn --version;
            yarn install --pure-lockfile;
            yarn generate-schema;
            yarn build;
            pm2 stop api;
            pm2 delete api;
            pm2 start packages/api/dist/index.js --name api;"

workflows:
  build:
    jobs:
      - test_and_build
